### ISSUE TITLE
no updates

### ISSUE THREAD

**Issue by zxcat** [ypid-bot/doublecmd#1]
Official Double Commander SVN is at revision 6543 now. But this repo is @6487 (>week ago).
Looks like something broken

**Comment by ypid** [comment]
Thanks for the hint :wink: Server on which this is running is currently offline. Will come back online in a few weeks. Or is this little "mirror service" more important for you?

**Comment by zxcat** [comment]
Just planning to add/fix something in DC to make work with is faster.
And making this on GitHub is much easier (PullRequests, etc...) than in sourceforge svn.
Maybe DC author will move to Git officially if see some pull requests here : )

**Comment by ypid** [comment]
There is already a discussion about this :wink: http://doublecmd.sourceforge.net/forum/viewtopic.php?f=5&t=1742&sid=fdb299690acf6a2633cdefd0313829a3&start=20 I agree. A few PR might get the devs interested :smile: Unfortunately, the server is located somewhere else. I will put it back online when possible. I am not sure what happens when I run the svn import again if the root commit and so on will be the same. There is also another "fork" but it is also outdated. Looks like he is merging from me. I suggest to import it again https://github.com/ypid-bot/setup until I am up-to-date again. I don’t really want to deal with svn more than necessary :wink:

**Comment by ypid** [comment]
I am up-to-date again. Feel free to open PRs :wink:
