### ISSUE TITLE
is there an option of mirror navigation?

### ISSUE THREAD

**Issue by ghost** [ypid-bot/doublecmd#3]
Enter a folder with the same name in second panel?

**Comment by ypid** [comment]
When by "same name" you mean same path then `cm_TargetEqualSource` which is mapped to Alt+Z by default should this.

Note that this issue tracker is nor a help forum nor the upstream issue tracker. Refer to: #2. Please tell me what lead you into opening an issue here so that I can fix the misunderstanding. Anyway, I hope this helps but note that such questions are meant to be answered by the documentation or by figuring it out yourself 😉
